#!/usr/bin/bash
# Copyright (c) 2025 dare3path
# Licensed under the Apache License 2.0 (see LICENSE-APACHE.txt)
# Licensed under the Business Source License 1.1 (see LICENSE-BSL.txt)
# Licensed under the MIT License (see LICENSE-MIT.txt)
# Use any one of these licenses at your option.

SERVER_CERT_DAYS=365

#generate self-signed server certificate
openssl req -x509 -new -key server.key -out serverSS.crt -sha256 -days "$SERVER_CERT_DAYS" -nodes -config san.cnf

#XXX: this will NOT work:
#openssl verify -CAfile ca.crt serverSS.crt

#this will work:
openssl verify -CAfile serverSS.crt serverSS.crt

