#!/usr/bin/bash
# Copyright (c) 2025 dare3path
# Licensed under the Apache License 2.0 (see LICENSE-APACHE.txt)
# Licensed under the Business Source License 1.1 (see LICENSE-BSL.txt)
# Licensed under the MIT License (see LICENSE-MIT.txt)
# Use any one of these licenses at your option.

set -e

#Create a Certificate Signing Request (CSR) for the Server: 
#openssl req -new -key server.key -out server.csr -subj "/CN=localhost"
#openssl req -new -key server.key -out server.csr -config san.cnf -subj "/CN=localhost"
openssl req -new -key server.key -out server.csr -config san.cnf

#    -subj "/CN=localhost": Sets the server’s CN to “localhost” (use your domain if different, e.g., /CN=example.com).
#    Output: server.csr—the Certificate Signing Request (temporary file).

#Verify the CSR (Optional)
openssl req -in server.csr -noout -text | grep -i localhost

echo "all done."
