#!/usr/bin/bash
# Copyright (c) 2025 dare3path
# Licensed under the Apache License 2.0 (see LICENSE-APACHE.txt)
# Licensed under the Business Source License 1.1 (see LICENSE-BSL.txt)
# Licensed under the MIT License (see LICENSE-MIT.txt)
# Use any one of these licenses at your option.

#this will work:
openssl verify -CAfile ca.crt server.crt
#XXX: this will NOT work:
#openssl verify -CAfile server.crt server.crt

#show the server cert(public) which was signed by the local CA
openssl x509 -in server.crt -noout -text | less

if test -f "serverSS.crt"; then
  #this will work:
  openssl verify -CAfile serverSS.crt serverSS.crt
  openssl x509 -in serverSS.crt -noout -text | less
fi
